<?php
/**
 * @var \Mikielis\StockCallUs\Helper\Data
 */
$helper = $this->helper('Mikielis\StockCallUs\Helper\Data');
$callUsMessage = $helper->getMessage();

/**
 * @var $block \Magento\Catalog\Block\Product\View\AbstractView
 */
$_product = $block->getProduct();
?>


<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
        <?php if ($callUsMessage): ?>
            <div class="stock-call-us"><?php echo $callUsMessage ?></div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
